Repository myungjin-likes-tuna/checkareer-core-spring, pull requests merged in 2022-03, with the labels that each got.

#24 fix: 데이터 타입 Long -> String 변경
  domain/src/main/kotlin/com/mlt/checkareercorespring/domain/user/model/dto/UserGetResponse.kt
  domain/src/main/kotlin/com/mlt/checkareercorespring/domain/user/model/dto/UserSaveRequest.kt
  domain/src/main/kotlin/com/mlt/checkareercorespring/domain/user/model/dto/UserSkillSimilarityGetResponse.kt
  domain/src/main/kotlin/com/mlt/checkareercorespring/domain/user/model/entity/User.kt
  domain/src/main/kotlin/com/mlt/checkareercorespring/domain/user/repository/UserRepository.kt
  domain/src/main/kotlin/com/mlt/checkareercorespring/domain/user/service/UserService.kt
  http/user.http
  web/src/main/kotlin/com/mlt/checkareercorespring/controller/UserController.kt
Labels: fix

#27 fix: 빌드 스크립트 오류 해결
  deploy/deploy.sh
Labels: bug

#28 fix: 빌드 스크립트 오류 해결
  deploy/deploy.sh
Labels: bug

#32 fix: 배포시 발생한 문제 해결 bug
  deploy/deploy.sh
  http/user.http
  infra/src/main/kotlin/com/mlt/checkareercorespring/infra/firebase/FirebaseConfig.kt
  web/src/main/kotlin/com/mlt/checkareercorespring/interceptor/CheckPermissionInterceptor.kt
Labels: bug

#33 fix: interceptor 통과 조건 추가
  web/src/main/kotlin/com/mlt/checkareercorespring/interceptor/CheckPermissionInterceptor.kt
Labels: bug

#36 feature: 유사 스킬 유저목록 조회 인가 추가
  http/user.http
  web/src/main/kotlin/com/mlt/checkareercorespring/controller/UserController.kt
Labels: feature
